services:

    app.sylius_clic_and_pay:
        class: Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder
        argument: Poliofu\SyliusClicAndPayPlugin\Payum\SyliusPaymentGatewayFactory
        tags:
            - { name: payum.gateway_factory_builder, factory: sylius.clic_and_pay }

    Poliofu\SyliusClicAndPayPlugin\Form\Type\SyliusGatewayConfigurationType:
        tags:
            - { name: sylius.gateway_configuration_type, type: sylius_payment, label: Clic&Play }
            - { name: form.type }

    Poliofu\SyliusClicAndPayPlugin\Payum\Action\CaptureAction:
        public: true
        argument:
            - { type: service, id: sylius.http_client }
        tags:
            - { name: payum.action, factory: sylius.clic_and_pay, alias: payum.action.capture }